-- Sliding window log rate limiter.
--
-- KEYS[1] = window key (sorted set: member -> timestamp score, ms)
-- ARGV[1] = limit
-- ARGV[2] = window, in milliseconds
-- ARGV[3] = key TTL in seconds
-- ARGV[4] = member id — random bytes generated by the Go caller, unique
--           per call
--
-- Returns {allowed, remaining, retry_after_ms, reset_ms} where
-- retry_after_ms and reset_ms are both relative to "now".
--
-- Why the member id comes from the client instead of Redis: what has to
-- come from Redis is TIME. Two gateway instances with skewed clocks
-- computing "now" themselves would disagree about which entries are still
-- inside the window, which breaks the whole guarantee. Identity doesn't
-- have that constraint — a sorted-set member only needs to not collide
-- with any other member in this key, not agree with any other machine.
-- Random bytes from any client satisfy that regardless of clock
-- resolution. Earlier attempts tried to derive uniqueness on the Redis
-- side: a second INCR-based counter key was Cluster-unsafe (a key built by
-- string concatenation inside the script is never declared in KEYS[], and
-- cluster-mode Redis requires every key a script touches to be there), and
-- switching to TIME's microseconds alone wasn't actually unique — replayed
-- under test, 100 concurrent same-key requests allowed 13-14 through
-- instead of exactly 10, because enough script invocations landed in the
-- same microsecond to collide. A client-supplied random id sidesteps both:
-- the script stays single-key (KEYS[1] only, Cluster-safe) and doesn't
-- need a second TTL to keep in sync with the main key.

local limit = tonumber(ARGV[1])
local window_ms = tonumber(ARGV[2])
local ttl_ms = tonumber(ARGV[3]) * 1000
local member_id = ARGV[4]

-- Time must come from Redis, never from the caller — see above.
local time_parts = redis.call('TIME')
local now_ms = math.floor(tonumber(time_parts[1]) * 1000 + tonumber(time_parts[2]) / 1000)

-- Drop entries that have already aged out of the window.
redis.call('ZREMRANGEBYSCORE', KEYS[1], 0, now_ms - window_ms)

local count = redis.call('ZCARD', KEYS[1])

local allowed = 0
local retry_after_ms = 0

if count < limit then
  allowed = 1
  count = count + 1

  local member = now_ms .. ':' .. member_id
  redis.call('ZADD', KEYS[1], now_ms, member)
else
  local oldest = redis.call('ZRANGE', KEYS[1], 0, 0, 'WITHSCORES')
  if oldest[2] then
    retry_after_ms = (tonumber(oldest[2]) + window_ms) - now_ms
    if retry_after_ms < 0 then
      retry_after_ms = 0
    end
  end
end

redis.call('PEXPIRE', KEYS[1], ttl_ms)

local remaining = limit - count
if remaining < 0 then
  remaining = 0
end

-- reset_ms: time until the window is completely empty again, i.e. until
-- the most recent entry ages out.
local reset_ms = 0
local newest = redis.call('ZREVRANGE', KEYS[1], 0, 0, 'WITHSCORES')
if newest[2] then
  reset_ms = (tonumber(newest[2]) + window_ms) - now_ms
  if reset_ms < 0 then
    reset_ms = 0
  end
end

return {allowed, remaining, retry_after_ms, reset_ms}
